### ISSUE TITLE
Prepend markdowns with numbers 

### ISSUE THREAD

**Issue by palladius** [meteatamel/gemini-code-assist-tour#2]
Mete, I'm looking at your awesome codelab.
I find it hard to navigate as I have to click on README and each click brings me to a different doc.

Wouldnt it be better if pages where named numerically like:

* setup.md => 01-setup.md 
* design-app.md => 02-design-app.md
* ...

**Comment by palladius** [comment]
(clicked to fast)

This way I can just go to https://github.com/meteatamel/gemini-code-assist-tour/tree/main/docs both on web or on my vscode and just navigate in order.

**Comment by meteatamel** [comment]
I had that kind of numbering before but experience tells me that it's hard to maintain numbering. Every time I add a new step at the beginning or in the middle, I have to rename all the files. To avoid that, I simply don't use numbering and I maintain order in README.md, much easier to maintain
